apiVersion: v2
kubeVersion: ">=1.16.0-0"
name: mymediaforalexa
version: 0.0.6
appVersion: "1.3.147.994"
description: This is the multi-platform Docker image for My Media for Alexa - https://www.mymediaalexa.com .
type: application
deprecated: false
home: https://github.com/truecharts/charts/tree/master/charts/incubator/mymediaforalexa
icon: https://raw.githubusercontent.com/Xstar97/NoobCatalog/main/imgs/mymediaforalexa.png
keywords:
  - media
  - alexa
sources:
  - https://hub.docker.com/r/bizmodeller/mymediaforalexa
  - https://www.mymediaalexa.com/home/docker#dockerhub
dependencies:
  - name: common
    repository: https://library-charts.truecharts.org
    version: 10.4.8
    # condition:
maintainers:
  - email: info@truecharts.org
    name: TrueCharts
    url: https://truecharts.org
annotations:
  truecharts.org/catagories: |
    - media
  truecharts.org/SCALE-support: "true"
  truecharts.org/grade: U
